<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <LangVersion>12</LangVersion>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageIcon>Icon.jpg</PackageIcon>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
    <EmbeddedResource Include="Views\Fixed\ClassAttribute.hbs" LogicalName="ClassAttribute.hbs" />
    <EmbeddedResource Include="Views\Fixed\ParameterAttribute.hbs" LogicalName="ParameterAttribute.hbs" />
    <None Include="..\..\img\Icon.jpg">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <PackageReference Include="Boxed.Mapping" PrivateAssets="all" />
    <PackageReference Include="Handlebars.Net" PrivateAssets="all" />
    <PackageReference Include="AutoInterface">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Nullable">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="CodeCasing" />
    <PackageReference Include="Microsoft.CSharp" PrivateAssets="all" />
    <PackageReference Include="SourceGenerator.Foundations" PrivateAssets="all" />
    <!-- We pin the version [4.7.0] to ensure compatibility with Visual Studio 2022 -->
    <PackageReference Include="Microsoft.CodeAnalysis.Common" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
  </ItemGroup>
</Project>