name: Publish

on:
  release:
    types: [published]
  workflow_dispatch: {}

env:
  Configuration: Release
jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        project: 
          - name: AutoFactories
          - name: AutoFactories.Ninject
          - name: AutoFactories.Microsoft.DependencyInjection
    steps:
      - name: CheckOut
        uses: ByronMayne/Shared.Actions/gitversion_checkout@1.0.5
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Build | ${{ matrix.project.name }}
        uses: ByronMayne/Shared.Actions/build_csharp@1.0.5
        with: 
          publish: false 
          configuration: ${{ env.configuration }}
          solutionOrProjectPath: /src/${{ matrix.project.name }}/${{ matrix.project.name }}.csproj
      - name: Publish 
        uses: ByronMayne/Shared.Actions/publish_csharp_nuget@1.0.5
        with: 
          publish: true 
          configuration: ${{ env.configuration }}
          solutionOrProjectPath: /src/${{ matrix.project.name }}/${{ matrix.project.name }}.csproj
          nugetApiKey: ${{ secrets.NUGET_API_KEY }}